version: '2.1'
services:
  payment_manager:
    build: .
    command: ./bin/www
    volumes:
      - .:/build
      - /build/node_modules
    ports:
      - "3402:3402"
    depends_on:
      - mongo
      - redis
      - nano
    environment:
      MONGO_URI: mongodb://mongo/payment_manager
      REDIS_URI: redis://redis:6379/
      DEBUG: "${DEBUG}"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ../../data/mongo:/data/db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ../../data/redis:/data
  nano:
    image: "nanocurrency/nano"
    ports:
      - "7075:7075/udp"
      - "7075:7075"
      - "7076:7076"
    volumes:
      - ../../data/nano:/root
